// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)
